services:
  - type: web
    name: verdora-ai-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_VISION_MODEL
        value: gpt-4o-mini
      - key: OPENAI_API_KEY
        sync: false
      - key: FIREBASE_ADMIN_CREDENTIALS
        sync: false
